version: '3.9'
services:
  mongo-rs:
    image: mongo:${MONGODB_VERSION:-4.4}
    container_name: mongo-rs
    restart: always
    volumes:
      - ./rs-initiate.js:/docker-entrypoint-initdb.d/rs-initiate.js
    ports:
      - 27117:27117
    command:
      - --replSet
      - rs0
      - --bind_ip_all
      - --port
      - '27117'
