name: Test tap-mongodb
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/validate.yml
      - .pre-commit-config.yaml
      - meltano.yml
      - tap_mongodb/**
      - tests/**
      - pyproject.toml
      - uv.lock
  pull_request:
    paths:
      - .github/workflows/validate.yml
      - .pre-commit-config.yaml
      - meltano.yml
      - tap_mongodb/**
      - tests/**
      - pyproject.toml
      - uv.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: '1'
  MELTANO_VERSION: 4.2.2

permissions: {}

jobs:
  build-package:
    name: Build & verify package
    runs-on: ubuntu-latest
    outputs:
      supported-python-versions: ${{ steps.baipp.outputs.supported_python_classifiers_json_array }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: hynek/build-and-inspect-python-package@2abe76da66d0a6a4a227101f9348ee855797cfa5 # v3.0.1
        id: baipp

  pre-commit:
    name: Linting and formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - name: Run pre-commit checks
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1

  smoke-test:
    name: Meltano Smoke Test
    runs-on: ubuntu-latest
    needs: build-package
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(needs.build-package.outputs.supported-python-versions) }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - name: Set up uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install meltano
        run: uv tool install --with meltano=="${MELTANO_VERSION}" meltano
      - name: Smoke test
        run: meltano invoke tap-mongodb --about

  test:
    name: Tap Tests
    runs-on: ubuntu-latest
    needs: build-package
    strategy:
      fail-fast: false
      matrix:
        mongo-version:
          - '8.0'
        python-version: ${{ fromJson(needs.build-package.outputs.supported-python-versions) }}
        include:
          - mongo-version: '7.0'
            python-version: '3.14'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - name: Set up uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          uv sync
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@315db7fe45ac2880b7758f1933e6e5d59afd5e94  # 1.12.1
        with:
          mongodb-version: ${{ matrix.mongo-version }}
          mongodb-username: admin
          mongodb-password: password
          mongodb-db: test
      - name: Test with pytest
        run: uv run pytest

  integration:
    name: Meltano integration test 🐉
    runs-on: ubuntu-latest
    env:
      DATABASE: test
      USERNAME: admin
      PASSWORD: password
    strategy:
      fail-fast: false
      matrix:
        mongodb-version:
          - '7.0'
          - '8.0'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@315db7fe45ac2880b7758f1933e6e5d59afd5e94  # 1.12.1
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-username: ${{ env.USERNAME }}
          mongodb-password: ${{ env.PASSWORD }}
          mongodb-db: ${{ env.DATABASE }}
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1
      - name: Install Meltano
        run: uv tool install --with meltano=="${MELTANO_VERSION}" meltano
      - run: >
          uv run scripts/seed.py
          --host localhost
          --port 27017
          --database "${DATABASE}"
          --username "${USERNAME}"
          --password "${PASSWORD}"
      - run: meltano run tap-mongodb target-jsonl
        env:
          TAP_MONGODB_DATABASE: ${{ env.DATABASE }}
          TAP_MONGODB_MONGODB_CONNECTION_STRING: mongodb://${{ env.USERNAME }}:${{ env.PASSWORD }}@localhost:27017/
